### ISSUE TITLE
KeyError: 'elementid'

### ISSUE THREAD

**Issue by ghost** [Prototype-X/Zabbix-Network-Weathermap#15]
I can not create a configuration file. Please help me find the reason.

```
Traceback (most recent call last):
  File "./weathermap.py", line 121, in <module>
    main()
  File "./weathermap.py", line 118, in main
    WeathermapCLI()
  File "./weathermap.py", line 55, in __init__
    self._map_scan()
  File "./weathermap.py", line 69, in _map_scan
    scan_map.create()
  File "/opt/Zabbix-Network-Weathermap/config.py", line 244, in create
    nodename = self.dict_call[int(node['elementtype'])](node['elementid'])
KeyError: 'elementid'
```
```
pip3 show py-zabbix
Name: py-zabbix
Version: 1.1.3
Summary: Python module to work with zabbix.
Home-page: https://github.com/blacked/py-zabbix
Author: Alexey Dubkov
Author-email: alexey.dubkov@gmail.com
License: UNKNOWN
Location: /usr/lib/python3.4/site-packages
Requires:
```
```
pip3 show urllib3
Name: urllib3
Version: 1.22
Summary: HTTP library with thread-safe connection pooling, file post, and more.
Home-page: https://urllib3.readthedocs.io/
Author: Andrey Petrov
Author-email: andrey.petrov@shazow.net
License: MIT
Location: /usr/lib/python3.4/site-packages
Requires:
```
```
lsb_release -d
Description:    CentOS Linux release 7.3.1611 (Core)
```
```
zabbix_server --version
zabbix_server (Zabbix) 3.4.1
Revision 71734 28 August 2017, compilation time: Aug 28 2017 10:10:28
```

**Comment by Prototype-X** [comment]
Hi,
Zabbix API changed in version Zabbix 3.4. This is the reason why it does not work.

**Comment by Prototype-X** [comment]
Fixed
