### ISSUE TITLE
Error in template whatermap items

### ISSUE THREAD

**Issue by psmartins** [Prototype-X/Zabbix-Network-Weathermap#27]
Maxim,

Can you tell me the cause of the error below?

Value "Traceback (most recent call last):
File "/opt/zabbix/mapas_wheatermap_zabbix/weathermap.py", line 121, in <module>
main()
File "/opt/zabbix/mapas_wheatermap_zabbix/weathermap.py", line 118, in main
WeathermapCLI()
File "/opt/zabbix/mapas_wheatermap_zabbix/weathermap.py", line 53, in __init__
self._map_img()
File "/opt/zabbix/mapas_wheatermap_zabbix/weathermap.py", line 94, in _map_img
cfg = ConfigLoader(self.cfg_path + '/' + map_fn)
File "/opt/zabbix/mapas_wheatermap_zabbix/config.py", line 52, in __init__
self.load(path_cfg)
File "/opt/zabbix/mapas_wheatermap_zabbix/config.py", line 61, in load
self.check()
File "/opt/zabbix/mapas_wheatermap_zabbix/config.py", line 69, in check
for node in sorted([node for node in self.cfg_dict.keys() if cfg_sect in node]):
AttributeError: 'NoneType' object has no attribute 'keys'
0.221" of type "string" is not suitable for value type "Numeric (float)"

Thanks

**Comment by Prototype-X** [comment]
Error in the configuration file, in the section "node-".
Lost required options in "node-"
"node-" have 5 options:

1. name - required
2. label - optional
3. icon - optional
4. x - required
5. y - required

**Comment by psmartins** [comment]
Prototype-X

My map is working perfectly.

Thank you so much
