### ISSUE TITLE
Zabbix on centos - IP for server

### ISSUE THREAD

**Issue by dynochu** [Prototype-X/Zabbix-Network-Weathermap#28]
Having difficulty setting up weather map using zabbix on a centos VM.
How to create file with map configuration using an IP for server url?

**Comment by Prototype-X** [comment]
Just like a domain name in url.
``` weathermap.py -s mapname1 mapnameN -z http://1.1.1.1/zabbix -l login -p password```

**Comment by dynochu** [comment]
Am getting the following errors after running that command

while scanning a simple key
  in "/opt/Zabbix-Network-Weathermap-master/mapcfgs/test.yaml", line 7, column 9
could not find expected ':'
  in "/opt/Zabbix-Network-Weathermap-master/mapcfgs/test.yaml", line 8, column 9
Traceback (most recent call last):
  File "/opt/Zabbix-Network-Weathermap-master/config.py", line 108, in check
    self.cfg_dict[cfg_sect][cfg_opt]
KeyError: 'zabbix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./weathermap.py", line 121, in <module>
    main()
  File "./weathermap.py", line 118, in main
    WeathermapCLI()
  File "./weathermap.py", line 55, in __init__
    self._map_scan()
  File "./weathermap.py", line 70, in _map_scan
    scan_map.check_map(self.cfg_path)
  File "/opt/Zabbix-Network-Weathermap-master/config.py", line 341, in check_map
    self._compare(old_cfg_path_fn)
  File "/opt/Zabbix-Network-Weathermap-master/config.py", line 345, in _compare
    self.cfg_loader_obj = ConfigLoader(old_cfg_path_file)
  File "/opt/Zabbix-Network-Weathermap-master/config.py", line 52, in __init__
    self.load(path_cfg)
  File "/opt/Zabbix-Network-Weathermap-master/config.py", line 61, in load
    self.check()
  File "/opt/Zabbix-Network-Weathermap-master/config.py", line 114, in check
    raise ConfigException('The option: {0} is missing in section: [{1}]'.format(cfg_sect, cfg_opt))
config.ConfigException: The option: zabbix is missing in section: [password]

**Comment by Prototype-X** [comment]
Errors in the file test.yaml, which was created manually.
```rm -f /opt/Zabbix-Network-Weathermap-master/mapcfgs/test.yaml```

**Comment by dynochu** [comment]
Thank you. Am able to create the file already.
Am now stuck with errors for the itemin and itemout for the link.
Can you please explain that part to me? What should be placed for itemin and itemout?
Sorry, am new at this.

**Comment by Prototype-X** [comment]
itemin/itemout it is traffic counters. Open zabbix ->Configuration-> Hosts -> Your host -> Items -> find items traffic counters -> copy their from column "key" -> set in configuration mapname.yaml
example:
```
      itemin: ifHCInOctets[ge-0/0/0]
      itemout: ifHCOutOctets[ge-0/0/0]
```
