### ISSUE TITLE
map: tetrion_map.cfg not found

### ISSUE THREAD

**Issue by lkthomas** [Prototype-X/Zabbix-Network-Weathermap#3]
./weathermap.py -s test_map.cfg -z http://abc.com -l admin -p admin
Traceback (most recent call last):
  File "./weathermap.py", line 123, in <module>
    main()
  File "./weathermap.py", line 120, in main
    WeathermapCLI()
  File "./weathermap.py", line 55, in **init**
    self._map_scan()
  File "./weathermap.py", line 67, in _map_scan
    map_data = zbx.scan_map(map_n)
  File "/opt/Zabbix-Network-Weathermap/zabbix.py", line 76, in scan_map
    raise ZbxException('map: {} not found'.format(map_name))
zabbix.ZbxException: map: test_map.cfg not found

**Comment by Prototype-X** [comment]
If you first time scan map and file test_map.cfg not exist, option -s is map name in zabbix, not file name.
For example: weathermap.py -s test_map -z http://abc.com -l admin -p admin

If you want rescan map and file test_map.cfg exist, then -s is map name use with option -f
For example: weathermap.py -s test_map -f

In the first case auth data get from cli arguments.
In the second case auth data get from file.

**Comment by giovanitestoni** [comment]
Hi, I have the same problem. I can't create a new map.
`# ./weathermap.py -s test_map teste_map -z http://0.0.0.0/zabbix -l admin -p admin
Traceback (most recent call last):
  File "./weathermap.py", line 121, in <module>
    main()
  File "./weathermap.py", line 118, in main
    WeathermapCLI()
  File "./weathermap.py", line 55, in __init__
    self._map_scan()
  File "./weathermap.py", line 67, in _map_scan
    map_data = zbx.scan_map(map_n)
  File "/opt/Zabbix-Network-Weathermap/zabbix.py", line 76, in scan_map
    raise ZbxException('map: {} not found'.format(map_name))
zabbix.ZbxException: map: test_map not found`

Can you help me?

Tks
