### ISSUE TITLE
Error when Create file with map configuration

### ISSUE THREAD

**Issue by tuananh9496** [Prototype-X/Zabbix-Network-Weathermap#32]
Hi Prototype-X,
I am new to use Zabbix. I install it on VMware Workstation (OS: CentOS 7).
I installed it as follows:
1. Create map in zabbix with two hosts and one link:

![image](https://user-images.githubusercontent.com/22422759/36520631-9c2eac40-17c4-11e8-81bd-fea25da429c9.png)

2. Save map
3. Scan map with the following command:
python3.6 weathermap.py -s newmap -z http://20.0.0.120/zabbix -l admin -p zabbix

and I have an error:

Traceback (most recent call last):
  File "weathermap.py", line 121, in <module>
    main()
  File "weathermap.py", line 118, in main
    WeathermapCLI()
  File "weathermap.py", line 55, in __init__
    self._map_scan()
  File "weathermap.py", line 69, in _map_scan
    scan_map.create()
  File "/opt/Zabbix-Network-Weathermap/config.py", line 252, in create
    nodename = self.dict_call[int(node['elementtype'])](node['elements'][0]['hostid'])
KeyError: 'elements'

Can you help me solve this problem? Sorry about my English.
Thank you!

**Comment by Prototype-X** [comment]
Hi,
What version of zabbix are you using?

**Comment by tuananh9496** [comment]
Hi, I use Zabbix 3.0.14.

**Comment by Prototype-X** [comment]
Ok, the last version 1.1.5 support Zabbix 3.4 - only, use previous [version 1.1.3](https://github.com/Prototype-X/Zabbix-Network-Weathermap/releases/tag/v1.1.3)

**Comment by tuananh9496** [comment]
I  installed Zabbix 1.1.3 and it works. Thank you.
But I have another question. What does "hostname", "itemin" and "itemout" mean?
This is my map:

![1](https://user-images.githubusercontent.com/22422759/36578593-d7e0f9ba-1890-11e8-937c-e2ce6392f780.PNG)

and this is my config file:

![2](https://user-images.githubusercontent.com/22422759/36579142-1a8e38e2-1894-11e8-9a55-240816d9519a.PNG)

Is that right?

**Comment by Prototype-X** [comment]
For example:
hostname - zabbix -> configuration -> hosts -> Zabbix server -> Host name
itemin/itemout - traffic counters   zabbix -> configuration -> hosts -> Zabbix server -> items -> column key -> net.if.in[eth0] and net.if.out[eth0]
Yes, that right.

**Comment by tuananh9496** [comment]
Thank you. I understood. 
I drew this map manually. Is there a way to draw network maps automatically with zabbix?

**Comment by igloo777** [comment]
Hi, +1 to the question of @tuananh9496
**Problem:** if we have 50+ links, it's obvious that we need something, that will get a values of "hostname:",   "itemin:", "itemout:" and "bandwidth:" from zabbix, because to add it into yaml config manually after changes in map.. it's a hell )

**How to implement:** we can use the fields "Label" of Map elements, and add there required info. 
So the Host, IN, OUT, Link in the values of Label can be used as a marker for parser.
Example: 
> Link: {sw20v:net.if.speed[ifHighSpeed.10202].last(0)}
> IN: {sw20v:net.if.in[ifHCInOctets.10202].last(0)}
> OUT: {sw20v-13e0:net.if.out[ifHCOutOctets.10202].last(0)}

I think it's should be easy to parse such data, and we have all required information for yaml!
Also there can be add mapping with multiplier (base*N*mult where base=2.5, N=bandwidth in Gbps, mult=0.5) like:
- 1 Gbps -> Width: 2.5x1x0.5 (1.25), Bandwidth: 1000
- 2 Gbps -> Width: 2.5, Bandwidth: 2000
- 3 Gbps -> Width: 3.75, Bandwidth: 2000
- ...
- 10 Gbps -> Width: 12.5, Bandwidth: 10000

For 40 and 100 Gbps links custom multiplier can be used. 

Weather map will still looks good:
![image](https://user-images.githubusercontent.com/15171310/40220219-96a772a4-5aa2-11e8-8f2b-9ed8c6c00e99.png)


@Prototype-X how do you think?
