### ISSUE TITLE
Error after changing interface agent from snmp to zabbix agent.

### ISSUE THREAD

**Issue by psmartins** [Prototype-X/Zabbix-Network-Weathermap#35]
Hello, Protoype-X

I started monitoring a linux firewall that was previously done via snmp and is now being done via zabbix agent and appeared two errors on the keys weathermap.update.only [{$ UPDATE}] and weathermap.update.upload [{$ UPLOAD}] . Below is the error:

Value "Traceback (most recent call last):
File "/opt/zabbix/mapas_wheatermap_zabbix/weathermap.py", line 121, in <module>
main()
File "/opt/zabbix/mapas_wheatermap_zabbix/weathermap.py", line 118, in main
WeathermapCLI()
File "/opt/zabbix/mapas_wheatermap_zabbix/weathermap.py", line 53, in __init__
self._map_img()
File "/opt/zabbix/mapas_wheatermap_zabbix/weathermap.py", line 95, in _map_img
map_obj = cfg.create_map(self.font_path_fn, self.icon_path)
File "/opt/zabbix/mapas_wheatermap_zabbix/config.py", line 161, in create_map
data_in, data_out = self.zbx.get_item_data2(hostname, item_in, item_out)
File "/opt/zabbix/mapas_wheatermap_zabbix/zabbix.py", line 60, in get_item_data2
raise ZbxException('item: {} not found'.format(item_in))
zabbix.ZbxException: item: net.if.in[ifHCInOctets.3] not found
5.628" of type "string" is not suitable for value type "Numeric (float)"

In map.yaml I made the following changes:

Before:

itemin: net.if.in [ifHCInOctets.3]
itemout: net.if.out [ifHCOutOctets.3]

Now:
  itemin: net.if.in [eth1]
  itemout: net.if.out [eth1]

NOTE: Before, via snmp was OK.

Thanks !

**Comment by psmartins** [comment]
I was able to solve the problem.

Thank you
