### ISSUE TITLE
config issues on Create file with map configuration

### ISSUE THREAD

**Issue by xingwenqin** [Prototype-X/Zabbix-Network-Weathermap#36]
Hi i hava stucked on this,can you help me. Thanks

weathermap.py -s mapname1 mapnameN -z http://zabbix.example.com -l admin -p admin
(has changed the parameter)

Traceback (most recent call last):
  File "./weathermap.py", line 121, in <module>
    main()
  File "./weathermap.py", line 118, in main
    WeathermapCLI()
  File "./weathermap.py", line 55, in __init__
    self._map_scan()
  File "./weathermap.py", line 67, in _map_scan
    map_data = zbx.scan_map(map_n)
  File "/opt/Zabbix-Network-Weathermap/zabbix.py", line 92, in scan_map
    raise ZbxException('map: {} not found'.format(map_name))

How do  I fix it. Thanks a lot!!

**Comment by Prototype-X** [comment]
Hi
`raise ZbxException('map: {} not found'.format(map_name))`
Wrong map name, check map name in parameters and in zabbix

**Comment by xingwenqin** [comment]
where to check map name in zabbix?

**Comment by Prototype-X** [comment]
Zabbix -> Monitoring -> Maps
