### ISSUE TITLE
Zabbix-Network-Weathermap

### ISSUE THREAD

**Issue by maheshzgde** [Prototype-X/Zabbix-Network-Weathermap#41]
I am getting following error  when i run the script weathermap.py  
I am using zabbix 4

root@ubuntu:/opt/Zabbix-Network-Weathermap-master# python3.5 weathermap.py -s test_map -z  http://127.0.0.1 -l admin -p  admin
Traceback (most recent call last):
  File "weathermap.py", line 10, in <module>
    from config import ConfigLoader, ConfigCreate
  File "/opt/Zabbix-Network-Weathermap-master/config.py", line 27
    class ConfigTemplate(metaclass=Singleton):  # noqa
                                  ^
SyntaxError: invalid syntax

**Comment by sarblaster** [comment]
Since upgrading to zabbix 4 our scripts have stopped working too, do we need to patch something to get them to work again?
