### ISSUE TITLE
unexpected keyword argument 'password'

### ISSUE THREAD

**Issue by jurim76** [Prototype-X/Zabbix-Network-Weathermap#45]
./weathermap.py -s my_mapname -z http://my_zabbix_server -l zabbix-api -p pass
or
./weathermap.py -s my_mapname -f

Traceback (most recent call last):
  File "./weathermap.py", line 121, in <module>
    main()
  File "./weathermap.py", line 118, in main
    WeathermapCLI()
  File "./weathermap.py", line 55, in __init__
    self._map_scan()
  File "./weathermap.py", line 66, in _map_scan
    zbx = ZabbixAgent(self.args.zabbix, self.args.login, self.args.pwd)
  File "/opt/Zabbix-Network-Weathermap/zabbix.py", line 23, in __init__
    self.zbx_api = ZabbixAPI(url=url, use_authenticate=False, user=login, password=password)
TypeError: __init__() got an unexpected keyword argument 'password'  (or unexpected keyword argument 'url', unexpected keyword argument 'user')

pyzabbix==0.7.5
Pillow==5.4.1
ruamel.yaml==0.14.12
python 3.4.3  debian jessie
zabbix 3.0

Same error for zabbix-network-weathermap 1.1.3 and 1.1.5
User zabbix-api has admin access on zabbix server  (login works)

**Comment by jurim76** [comment]
Invalid
